### ISSUE TITLE
Ubuntu with mono -> Word lists only first letter

### ISSUE THREAD

**Issue by schklom** [cmdwtf/KeePassDiceware#8]
On Ubuntu 20 LTS with Keepass 2.44 (most recent on Ubuntu) and mono installed, this plugin works as expected. The problem is that the word lists only appear with the first letter.

This is not breaking functionality, but more of an inconvenience.

![Screenshot from 2022-04-27 17-01-13](https://user-images.githubusercontent.com/23263086/165550707-b16dc377-2d94-40e8-b5b9-d45a7d2414c0.png)

**Comment by nitz** [comment]
How odd! Especially because the control used for the salt source is the same, and it doesn't seem to have a problem. I don't have a mono dev env setup at all, but I do have a debian based distro I've been using for some kernel dev, so I'll see if I can spin things up on it to be able to reproduce this.

**Comment by schklom** [comment]
Thanks :)

**Comment by nitz** [comment]
Hey @schklom — I just published a new version that added a bit for DPI scaling fixes, and I was curious if it changed any of this for you. Try out `v1.4.0` when you have some free time and let me know!

Cheers

**Comment by schklom** [comment]
@nitz Thanks for the update. Unfortunately, it did not fix my problem.
It does not bother me a lot, I picked the word lists to use based on KeePass on a Windows machine, and I have not needed to go through it again :P
